package ex_exception

fun main(args: Array<String>) {
    val str = "abcd"
    val num = str.toInt()

    println(num)
}